name: na-dpvi
channels:
  - defaults
dependencies:
  - python=3.10
  - pip:
    - jax==0.4.25
    - jaxlib==0.4.25
    - joblib==1.3.2
    - matplotlib==3.8.3
    - numba==0.59.1
    - numpy==1.26.4
    - numpyro==0.14.0
    - opacus==1.4.1
    - optax==0.2.1
    - optuna==3.6.0
    - pandas==1.3.5
    - plotly==5.4.0
    - scikit-learn==1.4.0
    - scipy==1.12.0
    - seaborn==0.13.2
    - tabulate==0.9.0
    - tqdm==4.67.1
    - tueplots==0.0.15
    - colorama==0.4.6
